'use client';

import React from 'react';
import { toast } from 'sonner';
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
    DialogFooter,
} from '@/components/ui/dialog';

/**
 * Result modal for a single generated document.
 *
 * Implementation note (important):
 * This component uses the shadcn / Radix `<Dialog>` primitive, which renders
 * into a portal attached to document.body and identifies state via
 * data-attributes (not class names). That gives us automatic protection
 * against the cross-page `.modal { display: none }` collisions we hit when
 * each dashboard page used to ship its own copy of the modal CSS in its
 * page-level stylesheet.
 *
 * Open/close is driven by the `open` prop. Pass `onClose` so the caller
 * stays the source of truth.
 *
 * Expected `doc` shape (matches what /document/generate returns):
 *   {
 *     id, title, content, provider, model, tone,
 *     documentType, clientId, createdAt,
 *     credits: { cost, balance_after }
 *   }
 */
const DocumentResultModal = ({ doc, open, onClose }) => {
    if (!doc) return null;

    const safeFileBase = (name) =>
        (name || 'document')
            .replace(/[^a-z0-9-_ ]/gi, '')
            .trim()
            .replace(/\s+/g, '-')
            .toLowerCase() || 'document';

    const escapeHtml = (s) =>
        String(s)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');

    const triggerDownload = (filename, mime, content) => {
        const blob = content instanceof Blob ? content : new Blob([content], { type: mime });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const handleCopy = async () => {
        if (!doc.content) return;
        try {
            await navigator.clipboard.writeText(doc.content);
            toast.success('Copied to clipboard');
        } catch {
            toast.error('Copy failed', { description: 'Select the text manually and copy.' });
        }
    };

    const handleDownloadTxt = () => {
        const base = safeFileBase(doc.title || doc.documentType);
        triggerDownload(`${base}.txt`, 'text/plain;charset=utf-8', doc.content);
    };

    const handleDownloadDoc = () => {
        const base = safeFileBase(doc.title || doc.documentType);
        const titleHtml = escapeHtml(doc.title || doc.documentType || 'Generated Document');
        const bodyHtml = escapeHtml(doc.content)
            .split(/\n{2,}/)
            .map((para) => `<p>${para.replace(/\n/g, '<br/>')}</p>`)
            .join('\n');

        const html = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head>
<meta charset="utf-8" />
<title>${titleHtml}</title>
<style>
body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; line-height: 1.5; color: #111; }
h1 { font-size: 16pt; margin-bottom: 8pt; }
p { margin: 0 0 10pt 0; }
.meta { color: #666; font-size: 9pt; margin-bottom: 14pt; }
</style>
</head>
<body>
<h1>${titleHtml}</h1>
<div class="meta">Generated by ClaimKing.AI — ${new Date().toLocaleString()}</div>
${bodyHtml}
</body>
</html>`;

        triggerDownload(`${base}.doc`, 'application/msword', html);
    };

    const handleDownloadPdf = () => {
        if (!doc.content) return;
        const titleHtml = escapeHtml(doc.title || doc.documentType || 'Generated Document');
        const bodyHtml = escapeHtml(doc.content)
            .split(/\n{2,}/)
            .map((para) => `<p>${para.replace(/\n/g, '<br/>')}</p>`)
            .join('\n');

        const win = window.open('', '_blank', 'width=800,height=900');
        if (!win) {
            toast.error('Pop-up blocked', {
                description: 'Allow pop-ups for this site to print as PDF.',
            });
            return;
        }
        win.document.open();
        win.document.write(`<!DOCTYPE html>
<html><head><meta charset="utf-8" />
<title>${titleHtml}</title>
<style>
@media print { @page { margin: 0.75in; } }
body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 12pt; line-height: 1.6; color: #111; max-width: 720px; margin: 24px auto; padding: 0 24px; }
h1 { font-size: 18pt; margin: 0 0 6pt 0; }
.meta { color: #666; font-size: 10pt; margin-bottom: 18pt; border-bottom: 1px solid #e5e7eb; padding-bottom: 10pt; }
p { margin: 0 0 12pt 0; }
</style>
</head>
<body>
<h1>${titleHtml}</h1>
<div class="meta">ClaimKing.AI — ${new Date().toLocaleString()}</div>
${bodyHtml}
<script>
window.onload = function () { setTimeout(function(){ window.focus(); window.print(); }, 200); };
</script>
</body></html>`);
        win.document.close();
    };

    const subtitleParts = [];
    if (doc.documentType && doc.documentType !== doc.title) subtitleParts.push(doc.documentType);
    if (doc.tone) subtitleParts.push(`Tone: ${doc.tone}`);

    return (
        <Dialog open={!!open} onOpenChange={(next) => { if (!next) onClose?.(); }}>
            <DialogContent style={{ maxWidth: '900px', width: '95%' }}>
                <DialogHeader className="flex flex-col gap-1.5 pr-8">
                    <DialogTitle className="break-words">
                        {doc.title || doc.documentType || 'Generated Document'}
                    </DialogTitle>
                    {subtitleParts.length > 0 && (
                        <DialogDescription>{subtitleParts.join(' · ')}</DialogDescription>
                    )}
                </DialogHeader>

                <div className="flex flex-wrap gap-3 text-xs text-gray-500 border-b border-dashed border-gray-200 pb-3 mb-1">
                    {doc.provider && <span>Provider: <strong className="text-gray-900 font-semibold">{doc.provider}</strong></span>}
                    {doc.model && <span>Model: <strong className="text-gray-900 font-semibold">{doc.model}</strong></span>}
                    {typeof doc?.credits?.cost === 'number' && (
                        <span>Credits used: <strong className="text-gray-900 font-semibold">{doc.credits.cost}</strong></span>
                    )}
                    {doc.createdAt && (
                        <span>Created: <strong className="text-gray-900 font-semibold">{new Date(doc.createdAt).toLocaleString()}</strong></span>
                    )}
                </div>

                <textarea
                    readOnly
                    value={doc.content || ''}
                    className="w-full min-h-[360px] max-h-[60vh] p-4 border border-gray-200 rounded-md bg-gray-50 text-gray-900 text-sm leading-relaxed resize-y font-[inherit]"
                />

                <DialogFooter className="sm:justify-start gap-2 flex-wrap">
                    <button
                        type="button"
                        className="flex-1 min-w-[120px] px-3 py-2 rounded-md border border-gray-300 bg-white text-gray-900 text-sm font-semibold hover:bg-gray-100 transition"
                        onClick={handleCopy}
                    >
                        Copy
                    </button>
                    <button
                        type="button"
                        className="flex-1 min-w-[120px] px-3 py-2 rounded-md bg-[#1a1f3a] text-white text-sm font-semibold hover:bg-[#0f1430] transition"
                        onClick={handleDownloadPdf}
                    >
                        Download PDF
                    </button>
                    <button
                        type="button"
                        className="flex-1 min-w-[120px] px-3 py-2 rounded-md border border-gray-300 bg-white text-gray-900 text-sm font-semibold hover:bg-gray-100 transition"
                        onClick={handleDownloadDoc}
                    >
                        Download .doc
                    </button>
                    <button
                        type="button"
                        className="flex-1 min-w-[120px] px-3 py-2 rounded-md border border-gray-300 bg-white text-gray-900 text-sm font-semibold hover:bg-gray-100 transition"
                        onClick={handleDownloadTxt}
                    >
                        Download .txt
                    </button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
};

export default DocumentResultModal;
