'use client';

import React, { useEffect } from 'react';
import { toast } from 'sonner';

/**
 * Dedicated modal that renders a single generated document.
 *
 * - Uses the centralized `.ck-modal*` styles (app/styles/modal.css) so it
 *   does not depend on the old `.modal` rules duplicated across each page's
 *   stylesheet.
 * - Pure presentational: it owns no fetch logic. Parent supplies the document
 *   payload and an onClose callback.
 *
 * Expected `doc` shape (matches what /document/generate returns):
 *   {
 *     id, title, content, provider, model, tone,
 *     documentType, clientId, createdAt,
 *     credits: { cost, balance_after }
 *   }
 */
const DocumentResultModal = ({ doc, onClose }) => {
    if (!doc) return null;

    // Close on Escape — better keyboard behavior than the old modal.
    useEffect(() => {
        const onKey = (e) => {
            if (e.key === 'Escape') onClose?.();
        };
        document.addEventListener('keydown', onKey);
        return () => document.removeEventListener('keydown', onKey);
    }, [onClose]);

    const safeFileBase = (name) =>
        (name || 'document')
            .replace(/[^a-z0-9-_ ]/gi, '')
            .trim()
            .replace(/\s+/g, '-')
            .toLowerCase() || 'document';

    const escapeHtml = (s) =>
        String(s)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');

    const triggerDownload = (filename, mime, content) => {
        const blob = content instanceof Blob ? content : new Blob([content], { type: mime });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const handleCopy = async () => {
        if (!doc.content) return;
        try {
            await navigator.clipboard.writeText(doc.content);
            toast.success('Copied to clipboard');
        } catch {
            toast.error('Copy failed', { description: 'Select the text manually and copy.' });
        }
    };

    const handleDownloadTxt = () => {
        const base = safeFileBase(doc.title || doc.documentType);
        triggerDownload(`${base}.txt`, 'text/plain;charset=utf-8', doc.content);
    };

    const handleDownloadDoc = () => {
        const base = safeFileBase(doc.title || doc.documentType);
        const titleHtml = escapeHtml(doc.title || doc.documentType || 'Generated Document');
        const bodyHtml = escapeHtml(doc.content)
            .split(/\n{2,}/)
            .map((para) => `<p>${para.replace(/\n/g, '<br/>')}</p>`)
            .join('\n');

        const html = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head>
<meta charset="utf-8" />
<title>${titleHtml}</title>
<style>
body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; line-height: 1.5; color: #111; }
h1 { font-size: 16pt; margin-bottom: 8pt; }
p { margin: 0 0 10pt 0; }
.meta { color: #666; font-size: 9pt; margin-bottom: 14pt; }
</style>
</head>
<body>
<h1>${titleHtml}</h1>
<div class="meta">Generated by ClaimKing.AI — ${new Date().toLocaleString()}</div>
${bodyHtml}
</body>
</html>`;

        triggerDownload(`${base}.doc`, 'application/msword', html);
    };

    const handleDownloadPdf = () => {
        if (!doc.content) return;
        const titleHtml = escapeHtml(doc.title || doc.documentType || 'Generated Document');
        const bodyHtml = escapeHtml(doc.content)
            .split(/\n{2,}/)
            .map((para) => `<p>${para.replace(/\n/g, '<br/>')}</p>`)
            .join('\n');

        const win = window.open('', '_blank', 'width=800,height=900');
        if (!win) {
            toast.error('Pop-up blocked', {
                description: 'Allow pop-ups for this site to print as PDF.',
            });
            return;
        }
        win.document.open();
        win.document.write(`<!DOCTYPE html>
<html><head><meta charset="utf-8" />
<title>${titleHtml}</title>
<style>
@media print { @page { margin: 0.75in; } }
body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 12pt; line-height: 1.6; color: #111; max-width: 720px; margin: 24px auto; padding: 0 24px; }
h1 { font-size: 18pt; margin: 0 0 6pt 0; }
.meta { color: #666; font-size: 10pt; margin-bottom: 18pt; border-bottom: 1px solid #e5e7eb; padding-bottom: 10pt; }
p { margin: 0 0 12pt 0; }
</style>
</head>
<body>
<h1>${titleHtml}</h1>
<div class="meta">ClaimKing.AI — ${new Date().toLocaleString()}</div>
${bodyHtml}
<script>
window.onload = function () { setTimeout(function(){ window.focus(); window.print(); }, 200); };
</script>
</body></html>`);
        win.document.close();
    };

    const handleOverlayClick = (e) => {
        if (e.target === e.currentTarget) onClose?.();
    };

    const subtitleParts = [];
    if (doc.documentType && doc.documentType !== doc.title) subtitleParts.push(doc.documentType);
    if (doc.tone) subtitleParts.push(`Tone: ${doc.tone}`);

    return (
        <div className="ck-modal-overlay" onClick={handleOverlayClick} role="dialog" aria-modal="true">
            <div className="ck-modal ck-modal--lg">
                <div className="ck-modal-header">
                    <div>
                        <h3 className="ck-modal-title">{doc.title || doc.documentType || 'Generated Document'}</h3>
                        {subtitleParts.length > 0 && (
                            <div className="ck-modal-subtitle">{subtitleParts.join(' · ')}</div>
                        )}
                    </div>
                    <button
                        type="button"
                        className="ck-modal-close"
                        onClick={onClose}
                        aria-label="Close"
                    >
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2">
                            <line x1="18" y1="6" x2="6" y2="18" />
                            <line x1="6" y1="6" x2="18" y2="18" />
                        </svg>
                    </button>
                </div>

                <div className="ck-modal-body">
                    <div className="ck-modal-meta">
                        {doc.provider && <span>Provider: <strong>{doc.provider}</strong></span>}
                        {doc.model && <span>Model: <strong>{doc.model}</strong></span>}
                        {typeof doc?.credits?.cost === 'number' && (
                            <span>Credits used: <strong>{doc.credits.cost}</strong></span>
                        )}
                        {doc.createdAt && (
                            <span>Created: <strong>{new Date(doc.createdAt).toLocaleString()}</strong></span>
                        )}
                    </div>

                    <textarea readOnly value={doc.content || ''} className="ck-modal-textarea" />
                </div>

                <div className="ck-modal-footer">
                    <button type="button" className="ck-btn ck-btn--secondary" onClick={handleCopy}>Copy</button>
                    <button type="button" className="ck-btn ck-btn--primary" onClick={handleDownloadPdf}>Download PDF</button>
                    <button type="button" className="ck-btn ck-btn--secondary" onClick={handleDownloadDoc}>Download .doc</button>
                    <button type="button" className="ck-btn ck-btn--secondary" onClick={handleDownloadTxt}>Download .txt</button>
                </div>
            </div>
        </div>
    );
};

export default DocumentResultModal;
